const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('patchwork', {
  chooseRepositories: () => ipcRenderer.invoke('repositories:choose'),
  chooseAttachments: () => ipcRenderer.invoke('attachments:choose'),
  listChatGPTProjects: () => ipcRenderer.invoke('projects:list'),
  createChatGPTProject: (name) => ipcRenderer.invoke('projects:create', name),
  listSkills: (repositoryPaths) => ipcRenderer.invoke('skills:list', repositoryPaths),
  listWorkspaceRepositories: () => ipcRenderer.invoke('workspace:list'),
  removeWorkspaceRepository: (repositoryPath) => ipcRenderer.invoke('workspace:remove', repositoryPath),
  gitStatus: (repositoryPath) => ipcRenderer.invoke('git:status', repositoryPath),
  gitStage: (repositoryPath, files) => ipcRenderer.invoke('git:stage', repositoryPath, files),
  gitStageAll: (repositoryPath) => ipcRenderer.invoke('git:stage-all', repositoryPath),
  gitUnstage: (repositoryPath, files) => ipcRenderer.invoke('git:unstage', repositoryPath, files),
  gitUnstageAll: (repositoryPath) => ipcRenderer.invoke('git:unstage-all', repositoryPath),
  gitCommit: (repositoryPath, message) => ipcRenderer.invoke('git:commit', repositoryPath, message),
  gitDiff: (repositoryPath, filePath, staged) => ipcRenderer.invoke('git:diff', repositoryPath, filePath, staged),
  gitSummary: (repositoryPath, customPrompt) => ipcRenderer.invoke('git:summary', repositoryPath, customPrompt),
  listTrees: () => ipcRenderer.invoke('trees:list'),
  revealTree: (treeId) => ipcRenderer.invoke('trees:reveal', treeId),
  removeTree: (treeId) => ipcRenderer.invoke('trees:remove', treeId),
  mergeTree: (treeId, chatgptProject) => ipcRenderer.invoke('trees:merge', treeId, chatgptProject),
  resolveTreeMerge: (treeId) => ipcRenderer.invoke('trees:resolve-merge', treeId),
  createTask: (input) => ipcRenderer.invoke('task:create', input),
  listTasks: () => ipcRenderer.invoke('task:list'),
  getTask: (taskId) => ipcRenderer.invoke('task:get', taskId),
  deleteTask: (taskId) => ipcRenderer.invoke('task:delete', taskId),
  openTask: (taskId) => ipcRenderer.invoke('task:open', taskId),
  submitTask: (taskId) => ipcRenderer.invoke('task:submit', taskId),
  setTaskTarget: (taskId, input) => ipcRenderer.invoke('task:set-target', taskId, input),
  useGitSummary: (taskId) => ipcRenderer.invoke('task:use-git-summary', taskId),
  resolveTaskConflict: (taskId, options) => ipcRenderer.invoke('task:resolve-conflict', taskId, options),
  copyPrompt: (taskId) => ipcRenderer.invoke('task:copy-prompt', taskId),
  revealPackage: (taskId) => ipcRenderer.invoke('task:reveal-package', taskId),
  importResult: (taskId) => ipcRenderer.invoke('task:import-result', taskId),
  applyTask: (taskId) => ipcRenderer.invoke('task:apply', taskId),
  retryApplyTask: (taskId) => ipcRenderer.invoke('task:retry-apply', taskId),
  rollbackTask: (taskId) => ipcRenderer.invoke('task:rollback', taskId),
  revealPath: (targetPath) => ipcRenderer.invoke('path:reveal', targetPath),
  setBrowserBounds: (bounds) => ipcRenderer.invoke('browser:set-bounds', bounds),
  setBrowserVisible: (visible) => ipcRenderer.invoke('browser:set-visible', visible),
  newChat: () => ipcRenderer.invoke('browser:new-chat'),
  reloadBrowser: () => ipcRenderer.invoke('browser:reload'),
  resetBrowserAuthentication: () => ipcRenderer.invoke('browser:reset-authentication'),
  browserBack: () => ipcRenderer.invoke('browser:back'),
  browserForward: () => ipcRenderer.invoke('browser:forward'),
  onTaskEvent: (listener) => {
    const handler = (_event, payload) => listener(payload);
    ipcRenderer.on('task:event', handler);
    return () => ipcRenderer.removeListener('task:event', handler);
  },
});
